# Generated by Django 4.2.6 on 2023-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_NUMBER', models.CharField(max_length=50)),
                ('CASE_STATUS', models.CharField(max_length=50)),
                ('VISA_CLASS', models.CharField(max_length=50)),
                ('EMPLOYER_NAME', models.CharField(max_length=50)),
                ('EMPLOYER_ADDRESS', models.CharField(max_length=50)),
                ('EMPLOYER_CITY', models.CharField(max_length=50)),
                ('EMPLOYER_STATE', models.CharField(max_length=50)),
                ('EMPLOYER_COUNTRY', models.CharField(max_length=50)),
                ('EMPLOYER_PROVINCE', models.CharField(max_length=50)),
                ('EMPLOYER_PHONE_EXT', models.CharField(max_length=50)),
                ('AGENT_ATTORNEY_NAME', models.CharField(max_length=50)),
                ('AGENT_ATTORNEY_CITY', models.CharField(max_length=50)),
                ('AGENT_ATTORNEY_STATE', models.CharField(max_length=50)),
                ('JOB_TITLE', models.CharField(max_length=50)),
                ('SOC_CODE', models.CharField(max_length=50)),
                ('SOC_NAME', models.CharField(max_length=50)),
                ('FULL_TIME_POSITION', models.CharField(max_length=50)),
                ('PW_UNIT_OF_PAY', models.CharField(max_length=50)),
                ('PW_WAGE_SOURCE', models.CharField(max_length=50)),
                ('PW_SOURCE_OTHER', models.CharField(max_length=50)),
                ('WAGE_UNIT_OF_PAY', models.CharField(max_length=50)),
                ('H1B_DEPENDENT', models.CharField(max_length=50)),
                ('WILLFULL_VIOLATOR', models.CharField(max_length=50)),
                ('WORKSITE_CITY', models.CharField(max_length=50)),
                ('WORKSITE_COUNTY', models.CharField(max_length=50)),
                ('WORKSITE_STATE', models.CharField(max_length=50)),
            ],
        ),
    ]
