# Generated by Django 4.2.6 on 2023-10-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_h1b_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h1b',
            name='salary',
            field=models.FloatField(max_length=100),
        ),
    ]
