# Generated by Django 4.2.6 on 2023-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_h1b_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h1b',
            name='salary',
            field=models.FloatField(),
        ),
    ]
