# Generated by Django 4.2.6 on 2023-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_h1b_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='h1b',
            name='unitofpay',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
