# from django.db import models

# class h1b(models.Model):
#     salary=models.FloatField()
#     unitofpay=models.CharField(max_length=100)

from django.db import models

class h1b(models.Model):
    salary = models.FloatField()
    unitofpay= models.CharField(max_length=100, null=True, blank=True)
    CASE_NUMBER= models.CharField(max_length=100, null=True, blank=True)
    CASE_STATUS= models.CharField(max_length=100, null=True, blank=True)
    CASE_SUBMITTED= models.CharField(max_length=100, null=True, blank=True)
    DECISION_DATE= models.CharField(max_length=100, null=True, blank=True)
    VISA_CLASS= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYMENT_START_DATE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYMENT_END_DATE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_NAME= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_ADDRESS= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_CITY= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_STATE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_POSTAL_CODE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_COUNTRY= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_PROVINCE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_PHONE= models.CharField(max_length=100, null=True, blank=True)
    EMPLOYER_PHONE_EXT= models.CharField(max_length=100, null=True, blank=True)
    AGENT_ATTORNEY_NAME= models.CharField(max_length=100, null=True, blank=True)
    AGENT_ATTORNEY_CITY= models.CharField(max_length=100, null=True, blank=True)
    AGENT_ATTORNEY_STATE= models.CharField(max_length=100, null=True, blank=True)
    JOB_TITLE= models.CharField(max_length=100, null=True, blank=True)
    SOC_CODE= models.CharField(max_length=100, null=True, blank=True)
    SOC_NAME= models.CharField(max_length=100, null=True, blank=True)
    NAIC_CODE= models.CharField(max_length=100, null=True, blank=True)
    TOTAL_WORKERS= models.CharField(max_length=100, null=True, blank=True)
    FULL_TIME_POSITION= models.CharField(max_length=100, null=True, blank=True)
    PW_WAGE_SOURCE= models.CharField(max_length=100, null=True, blank=True)
    PW_SOURCE_YEAR= models.CharField(max_length=100, null=True, blank=True)
    PW_SOURCE_OTHER= models.CharField(max_length=100, null=True, blank=True)
    WAGE_RATE_OF_PAY_FROM= models.CharField(max_length=100, null=True, blank=True)
    WAGE_RATE_OF_PAY_TO= models.CharField(max_length=100, null=True, blank=True)
    WAGE_UNIT_OF_PAY= models.CharField(max_length=100, null=True, blank=True)
    H_1B_DEPENDENT= models.CharField(max_length=100, null=True, blank=True)
    WILLFUL_VIOLATOR= models.CharField(max_length=100, null=True, blank=True)
    WORKSITE_CITY= models.CharField(max_length=100, null=True, blank=True)
    WORKSITE_COUNTY= models.CharField(max_length=100, null=True, blank=True)
    WORKSITE_STATE= models.CharField(max_length=100, null=True, blank=True)
    WORKSITE_POSTAL_CODE= models.CharField(max_length=100, null=True, blank=True)
    ORIGINAL_CERT_DATE= models.CharField(max_length=100, null=True, blank=True)