# Generated by Django 4.2.6 on 2023-10-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AddField(
            model_name='log',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='batch',
            field=models.IntegerField(blank=True, choices=[(2021, 'One'), (2022, 'Two'), (2023, 'Three'), (2024, 'Four'), (2025, 'Five')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Cse'), ('ECE', 'Ece'), ('EE', 'Ee'), ('MECH', 'Mech')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='city',
            field=models.CharField(blank=True, choices=[('chandigarh', 'Chandigarh'), ('panchkula', 'Panchkula'), ('mohali', 'Mohali'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='degree',
            field=models.CharField(blank=True, choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('Phd', 'Phd')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Kurukshetra', 'Kuk'), ('VIndhya', 'Vin'), ('Himalaya', 'Him'), ('Kalpana', 'Kal')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='prof',
            field=models.CharField(blank=True, choices=[('Cultural', 'Cult'), ('Technical', 'Tech'), ('Sports', 'Sport')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='quota',
            field=models.CharField(blank=True, choices=[('General', 'Gen'), ('SC', 'Sc'), ('ST', 'St'), ('OBC', 'Obc')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='scholar',
            field=models.CharField(blank=True, choices=[('none', 'Non'), ('Academic', 'Ac'), ('Sports', 'Sp'), ('PWD', 'Pwd')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
